# kubectl apply -f service.yml
apiVersion: v1
kind: Service
metadata:
  name: cristopherguzman-service
  namespace: cristopherguzman-namespace
  labels:
      app: microservice
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8087
      nodePort: 30088
  selector:
    app: microservice